# Generated by Django 5.1.7 on 2025-03-30 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('universidad', 'Universidad'), ('instituto', 'Instituto'), ('bootcamp', 'Bootcamp'), ('curso', 'Curso'), ('certificacion', 'Certificacion')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo_institucion', models.ImageField(blank=True, null=True, upload_to='logos_educacion/')),
            ],
            options={
                'verbose_name': 'Educación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('educacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='Educacion.educacion')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
