# Generated by Django 5.1.7 on 2025-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='tipo_contrato',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('freelance', 'Freelance'), ('practicas', 'Prácticas'), ('horario', 'Horario')], max_length=50),
        ),
    ]
